export const BIHAR_DISTRICTS = [
  { name: 'Patna', slug: 'patna' },
  { name: 'Gaya', slug: 'gaya' },
  { name: 'Bhagalpur', slug: 'bhagalpur' },
  { name: 'Muzaffarpur', slug: 'muzaffarpur' },
  { name: 'Darbhanga', slug: 'darbhanga' },
  { name: 'Bihar Sharif', slug: 'bihar-sharif' },
  { name: 'Purnia', slug: 'purnia' },
  { name: 'Katihar', slug: 'katihar' },
  { name: 'Saharsa', slug: 'saharsa' },
  { name: ' Hajipur', slug: 'hajipur' },
  { name: 'Chapra', slug: 'chapra' },
  { name: 'Motihari', slug: 'motihari' },
  { name: 'Bettiah', slug: 'bettiah' },
  { name: 'Bagaha', slug: 'bagaha' },
  { name: 'Siwan', slug: 'siwan' },
  { name: 'Gopalganj', slug: 'gopalganj' },
  { name: 'Nalanda', slug: 'nalanda' },
  { name: 'Nawada', slug: 'nawada' },
  { name: 'Jehanabad', slug: 'jehanabad' },
  { name: 'Aurangabad', slug: 'aurangabad' },
  { name: 'Madhubani', slug: 'madhubani' },
  { name: 'Samastipur', slug: 'samastipur' },
  { name: 'Begusarai', slug: 'begusarai' },
  { name: 'Jamui', slug: 'jamui' },
  { name: 'Kishanganj', slug: 'kishanganj' },
  { name: 'Araria', slug: 'araria' },
  { name: 'Supaul', slug: 'supaul' },
  { name: 'Madhepura', slug: 'madhepura' },
  { name: 'Khagaria', slug: 'khagaria' },
  { name: 'Munger', slug: 'munger' },
  { name: 'Lakhisarai', slug: 'lakhisarai' },
  { name: 'Sheikhpura', slug: 'sheikhpura' },
  { name: 'Kaimur', slug: 'kaimur' },
  { name: 'Rohtas', slug: 'rohtas' },
  { name: 'Buxar', slug: 'buxar' },
  { name: 'Ganga Dutt', slug: 'ganga-dutt' },
  { name: 'Vaishali', slug: 'vaishali' },
  { name: 'Saran', slug: 'saran' },
] as const;

export type BiharDistrict = typeof BIHAR_DISTRICTS[number]['slug'];